version: '3'
services:
  web:
    build: ./nginx
    container_name: nginx-dev
    hostname: project_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www/html
      - ./logs:/var/log/nginx
      - socket:/socket
    links:
      - php
  php:
    build: ./php
    container_name: php7.3-dev
    hostname: project_php
    volumes:
      - ./project:/var/www/html
volumes:
  socket: {}