version: '2'

services:
  web:
    build: ./nginx
    container_name: nginx-hw5.1
    hostname: project_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www/html
      - ./logs:/var/log/nginx
    links:
      - php

  php:
    build: ./php
    container_name: php7.4-hw5.1
    hostname: project_php
    volumes:
      - ./project:/var/www/html
    working_dir: /var/www/html