version: "3"

volumes:
  mongo_data:

services:
  php:
    build:
      context: ./docker/php 
    tty: true
    environment:
      - 'APP_PATH=${APP_PATH}'
      - 'MONGO_HOST=${MONGO_HOST}'
      - 'MONGO_PORT=${MONGO_PORT}'
      - 'MONGO_DB=${MONGO_DB}'
    volumes:
      - './app:${APP_PATH}'

  mongo:
    image: 'mongo:latest'
    restart: always
    volumes:
      - mongo_data:/data/db

