version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "${NGINX_HOST}:${NGINX_PORT}:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
    links:
      - php

  php:
    container_name: php
    build:
      context: docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    env_file: .env
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./app:/var/www/html