version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8282:80
    depends_on:
      - php-1
      - php-2
      - php-3
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/dev.mysite.conf:/etc/nginx/conf.d/default.conf

  php-1:
    container_name: php-fpm-1
    build:
      context: ./
      dockerfile: docker/php-1/Dockerfile
    volumes:
      - ./:/var/www/html

  php-2:
    container_name: php-fpm-2
    build:
      context: ./
      dockerfile: docker/php-2/Dockerfile
    volumes:
      - ./:/var/www/html

  php-3:
    container_name: php-fpm-3
    build:
      context: ./
      dockerfile: docker/php-3/Dockerfile
    volumes:
      - ./:/var/www/html
